# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'afk_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(200, 50, 331, 351))
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.auto_tower_btn = QtWidgets.QPushButton(self.gridFrame)
        self.auto_tower_btn.setObjectName("auto_tower_btn")
        self.gridLayout.addWidget(self.auto_tower_btn, 1, 0, 1, 1)
        self.auto_pai = QtWidgets.QPushButton(self.gridFrame)
        self.auto_pai.setObjectName("auto_pai")
        self.gridLayout.addWidget(self.auto_pai, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.device_combo_box = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.device_combo_box.sizePolicy().hasHeightForWidth())
        self.device_combo_box.setSizePolicy(sizePolicy)
        self.device_combo_box.setMinimumSize(QtCore.QSize(0, 26))
        self.device_combo_box.setObjectName("device_combo_box")
        self.horizontalLayout.addWidget(self.device_combo_box)
        self.connect_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_btn.sizePolicy().hasHeightForWidth())
        self.connect_btn.setSizePolicy(sizePolicy)
        self.connect_btn.setMinimumSize(QtCore.QSize(0, 27))
        self.connect_btn.setObjectName("connect_btn")
        self.horizontalLayout.addWidget(self.connect_btn)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.stop_all_btn = QtWidgets.QPushButton(self.gridFrame)
        self.stop_all_btn.setObjectName("stop_all_btn")
        self.gridLayout.addWidget(self.stop_all_btn, 3, 0, 1, 1)
        self.frame1 = QtWidgets.QFrame(self.gridFrame)
        self.frame1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame1.setObjectName("frame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame2 = QtWidgets.QFrame(self.frame1)
        self.frame2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio0 = QtWidgets.QRadioButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio0.sizePolicy().hasHeightForWidth())
        self.radio0.setSizePolicy(sizePolicy)
        self.radio0.setMouseTracking(True)
        self.radio0.setChecked(True)
        self.radio0.setObjectName("radio0")
        self.horizontalLayout_2.addWidget(self.radio0)
        self.radio1 = QtWidgets.QRadioButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio1.sizePolicy().hasHeightForWidth())
        self.radio1.setSizePolicy(sizePolicy)
        self.radio1.setObjectName("radio1")
        self.horizontalLayout_2.addWidget(self.radio1)
        self.radio2 = QtWidgets.QRadioButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio2.sizePolicy().hasHeightForWidth())
        self.radio2.setSizePolicy(sizePolicy)
        self.radio2.setObjectName("radio2")
        self.horizontalLayout_2.addWidget(self.radio2)
        self.radio3 = QtWidgets.QRadioButton(self.frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio3.sizePolicy().hasHeightForWidth())
        self.radio3.setSizePolicy(sizePolicy)
        self.radio3.setObjectName("radio3")
        self.horizontalLayout_2.addWidget(self.radio3)
        self.verticalLayout_2.addWidget(self.frame2)
        self.auto_challenge_btn = QtWidgets.QPushButton(self.frame1)
        self.auto_challenge_btn.setObjectName("auto_challenge_btn")
        self.verticalLayout_2.addWidget(self.auto_challenge_btn)
        self.gridLayout.addWidget(self.frame1, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 733, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.show_screen_action = QtWidgets.QAction(MainWindow)
        self.show_screen_action.setObjectName("show_screen_action")
        self.draw_sift_line_action = QtWidgets.QAction(MainWindow)
        self.draw_sift_line_action.setObjectName("draw_sift_line_action")
        self.print_distance_action = QtWidgets.QAction(MainWindow)
        self.print_distance_action.setObjectName("print_distance_action")
        self.menu.addAction(self.show_screen_action)
        self.menu.addAction(self.draw_sift_line_action)
        self.menu.addAction(self.print_distance_action)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.auto_tower_btn.setText(_translate("MainWindow", "自动爬塔"))
        self.auto_pai.setText(_translate("MainWindow", "自动抓牌"))
        self.connect_btn.setText(_translate("MainWindow", "连接"))
        self.stop_all_btn.setText(_translate("MainWindow", "终止所有操作"))
        self.radio0.setText(_translate("MainWindow", "0"))
        self.radio1.setText(_translate("MainWindow", "1"))
        self.radio2.setText(_translate("MainWindow", "2"))
        self.radio3.setText(_translate("MainWindow", "3"))
        self.auto_challenge_btn.setText(_translate("MainWindow", "自动挑战"))
        self.menu.setTitle(_translate("MainWindow", "调试"))
        self.show_screen_action.setText(_translate("MainWindow", "显示屏幕"))
        self.draw_sift_line_action.setText(_translate("MainWindow", "绘制特征线"))
        self.print_distance_action.setText(_translate("MainWindow", "打印特征"))
